# -*- coding: utf-8 -*-
"""BinaryObjectDetection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VB5_Th_4uqomv3GXr0LmDvuduxdC-uzC
"""


"""### TinyssimoYOLOv8 - binary detection"""

from ultralytics import YOLO

import matplotlib.pyplot as plt
import matplotlib.patches as patches
from matplotlib.lines import Line2D
from pathlib import Path
from PIL import Image

from bg_subtract import BgSubtractConfig, make_bg_subtract_trainer

# ── Background subtraction (optional preprocessing) ───────────────────────────
# Set USE_BG_SUBTRACTION = True to apply background subtraction on-the-fly
# inside the data loader.  No images are written to disk.
#
# ref_mode options:
#   "temporal" — diff each frame against its filename-sorted predecessor
#   "fixed"    — diff every frame against one fixed reference image;
#                set fixed_ref_path to an empty-scene image for this mode
USE_BG_SUBTRACTION = False
BG_SUBTRACT_CONFIG = BgSubtractConfig(
    ref_mode       = "fixed",          # "temporal" | "fixed"
    fixed_ref_path = "camera_B1_yolo/test/images/p_000037.jpg20180327.jpg",                # e.g. "camera_B1_yolo/p_000037.jpg20180327.jpg"
    use_blur       = True,
    diff_mode      = "absdiff",              # "absdiff" | "ssim"
    use_morph_open = True,
)
# ─────────────────────────────────────────────────────────────────────────────

# Load the pre-trained YOLOv8m (Medium) model
# The weights ('yolov8m.pt') will be downloaded automatically if not present
model = YOLO("runs/tinyissimoYOLOv8-binary-fulldataset-82split-excludetest-300eps/weights/best.pt")

# Fine-tune the model
print("Starting finetuning...")


# 8/2 inputs, default config
results = model.train(
    data="/home/lanmei/jrbp_ct_explorations/tinyissimoyolov8_cfgonly_binary/camera_B1_yolo/config.yaml",  # Path to your YAML configuration file
    epochs=200,               # Number of training epochs (adjust as needed)
    imgsz=640,                # Image size for training (640 is default)
    batch=32,                 # Batch size (reduce if you get Out of Memory errors)
    lr0=0.0001, # default 0.01
    lrf=0.01, # default 0.01
    device='1',                 # GPU device index (use 'cpu' if you don't have a GPU)
    project='/home/lanmei/jrbp_ct_explorations/tinyissimoyolov8_cfgonly_binary/runs/',
    name="tinyissimoYOLOv8-binary-fulldataset-82split-A2-300eps-finetune-82split-on-B1-200eps",    # Name of the folder where results will be saved
    **({"trainer": make_bg_subtract_trainer(BG_SUBTRACT_CONFIG)} if USE_BG_SUBTRACTION else {}),
)

'''

# 25 inputs, default config
results = model.train(
    data="/home/lanmei/jrbp_ct_explorations/tinyissimoyolov8_cfgonly_binary/camera_B1_yolo_25inputs/config.yaml",  # Path to your YAML configuration file
    epochs=200,               # Number of training epochs (adjust as needed)
    imgsz=640,                # Image size for training (640 is default)
    batch=32,                 # Batch size (reduce if you get Out of Memory errors)
    lr0=0.0001, # default 0.01
    lrf=0.01, # default 0.01
    device='1',                 # GPU device index (use 'cpu' if you don't have a GPU)
    project='/home/lanmei/jrbp_ct_explorations/tinyissimoyolov8_cfgonly_binary/runs/',
    name="tinyissimoYOLOv8-binary-fulldataset-82split-A2-300eps-finetune-25-on-B1-200eps",    # Name of the folder where results will be saved
    **({"trainer": make_bg_subtract_trainer(BG_SUBTRACT_CONFIG)} if USE_BG_SUBTRACTION else {}),
)

# 25 inputs, alternate config
results = model.train(
    data="/home/lanmei/jrbp_ct_explorations/tinyissimoyolov8_cfgonly_binary/camera_B1_yolo_25inputs/config.yaml",  # Path to your YAML configuration file
    epochs=200,
    imgsz=640,
    batch=4,                # Smaller batch size for tiny datasets
    lr0=0.0001,             # Much lower initial learning rate
    patience=30,
    freeze=10,             # Freeze the backbone
    warmup_epochs=0,       # Skip warmup
    optimizer='AdamW',     # Better optimizer for fine-tuning
    weight_decay=0.01,     # Heavier regularization to prevent overfitting
    mosaic=0.5,            # Reduce mosaic augmentation
    close_mosaic=20,       # Turn off mosaic for the last 20 epochsproject='/home/lanmei/jrbp_ct_explorations/tinyissimoyolov8_cfgonly_binary/runs/',
    name="tinyissimoYOLOv8-binary-fulldataset-82split-A2-300eps-finetune-25-on-B1-200eps-cfg2",    # Name of the folder where results will be saved
    **({"trainer": make_bg_subtract_trainer(BG_SUBTRACT_CONFIG)} if USE_BG_SUBTRACTION else {}),
)

'''
print("Training complete! Evaluating model...")

# Evaluate the model's performance on the validation set
metrics = model.val(project='/home/lanmei/jrbp_ct_explorations/tinyissimoyolov8_cfgonly_binary/runs/',
                    name="tinyissimoYOLOv8-binary-fulldataset-82split-A2-300eps-finetune-82split-on-B1-200eps-val", 
                    device="1",
                    )

# Run a quick prediction on a test image to verify
# model.predict("path/to/a/test/image.jpg", save=True)

# ── Paths ─────────────────────────────────────────────────────────────────────
# BEST_WEIGHTS   = "/home/lanmei/jrbp_ct_explorations/tinyissimoyolov8_cfgonly_binary/runs/tinyissimoYOLOv8-binary-best_500eps_on_A1-finetune_on_B1_25imgs-200eps/weights/best.pt"
TEST_IMAGES_DIR = Path("/home/lanmei/jrbp_ct_explorations/tinyissimoyolov8_cfgonly_binary/camera_B1_yolo/test/images")
TEST_LABELS_DIR = Path("/home/lanmei/jrbp_ct_explorations/tinyissimoyolov8_cfgonly_binary/camera_B1_yolo/test/labels")

# ── 1. Quantitative evaluation on the test split ──────────────────────────────
print("Evaluating on test set...")
test_metrics = model.val(
    data="/home/lanmei/jrbp_ct_explorations/tinyissimoyolov8_cfgonly_binary/camera_B1_yolo/config.yaml",
    split="test",
    project="/home/lanmei/jrbp_ct_explorations/tinyissimoyolov8_cfgonly_binary/runs/",
    name="tinyissimoYOLOv8-binary-fulldataset-82split-A2-300eps-finetune-82split-on-B1-200eps-test-on-B1",
    device="1",
) # tinyissimoYOLOv8-binary-500eps-test

print(f"\n── Test-set metrics ──────────────────────────")
print(f"  mAP@0.50      : {test_metrics.box.map50:.4f}")
print(f"  mAP@0.50:0.95 : {test_metrics.box.map:.4f}")
print(f"  Precision     : {test_metrics.box.mp:.4f}")
print(f"  Recall        : {test_metrics.box.mr:.4f}")

# ── 2. Visual spot-check: predictions vs ground truth on 6 test images ───────
def yolo_to_abs(cx, cy, bw, bh, W, H):
    """Convert YOLO normalised [cx, cy, w, h] → pixel [x1, y1, w, h]."""
    x1 = (cx - bw / 2) * W
    y1 = (cy - bh / 2) * H
    return x1, y1, bw * W, bh * H

test_images = sorted(TEST_IMAGES_DIR.glob("*.jpg"))[:6]
fig, axes = plt.subplots(2, 3, figsize=(15, 8))
fig.suptitle("Test set — predictions (red) vs ground truth (green)", fontsize=13)

for ax, img_path in zip(axes.flat, test_images):
    img = Image.open(img_path)
    W, H = img.size

    # Ground-truth boxes from label file
    gt_file = TEST_LABELS_DIR / (img_path.stem + ".txt")
    gt_boxes = []
    if gt_file.exists():
        for line in gt_file.read_text().splitlines():
            parts = line.strip().split()
            if len(parts) == 5:
                gt_boxes.append([float(v) for v in parts[1:]])

    # Model predictions
    preds = model.predict(str(img_path), conf=0.25, verbose=False)[0]

    ax.imshow(img)
    ax.set_title(img_path.name, fontsize=7)
    ax.axis("off")

    # Ground-truth in green
    for cx, cy, bw, bh in gt_boxes:
        x1, y1, pw, ph = yolo_to_abs(cx, cy, bw, bh, W, H)
        ax.add_patch(patches.Rectangle((x1, y1), pw, ph,
                                       linewidth=1.5, edgecolor="lime", facecolor="none"))

    # Predictions in red
    for box in preds.boxes:
        x1, y1, x2, y2 = box.xyxy[0].tolist()
        conf = box.conf[0].item()
        ax.add_patch(patches.Rectangle((x1, y1), x2 - x1, y2 - y1,
                                       linewidth=1.5, edgecolor="red", facecolor="none"))
        ax.text(x1, y1 - 3, f"{conf:.2f}", color="red", fontsize=6, fontweight="bold")

legend = [Line2D([0], [0], color="lime", lw=2, label="Ground truth"),
          Line2D([0], [0], color="red",  lw=2, label="Prediction")]
fig.legend(handles=legend, loc="lower center", ncol=2, fontsize=10)
plt.tight_layout()
plt.savefig("test_tinyissimoYOLOv8-binary-fulldataset-82split-A2-300eps-finetune-82split-on-B1-200eps-test-on-B1.png")
# plt.show()

